apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      volumes:
        - name: minikube-mount
          hostPath:
            path: /home/test
            type: DirectoryOrCreate
      containers:
        - name: node
          image: node
          ports:
            - containerPort: 3000
          command: [ "sleep" ]
          args: [ "1000000000" ]
          volumeMounts:
            - name: minikube-mount
              mountPath: /mnt/minikube

---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
